services:
  dev:
    build:
      context: ../../
      dockerfile: ./Dockerfile.dev
    container_name: task-server-dev-3000
    working_dir: /project-package
    ports:
      - 3000:3000
    environment:
      - USE_ENVVAR=true             
      - DB_HOST=172.17.0.1
      - DB_PORT=5434
      - DB_NAME=task
      - DB_TIMEZONE=Europe/London
      - DB_CONNECTIONS=10
      - DB_USERNAME=${DB_USER}
      # - DB_USERNAME=postgres # for kompose
      - DB_PASSWORD=${DB_PASSWORD}
      # - DB_PASSWORD=postgres # for kompose
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
    volumes:
      - ../../:/project-package/
    links:
      - db
    depends_on:
      - db
  db:
    build: .
    env_file: .env
    container_name: dev-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=task
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./data/db:/var/lib/postgres/data
version: "3.8"

