apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: goserver
  name: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: goserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.service.type: LoadBalancer
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/task-default: "true"
        io.kompose.service: goserver
    spec:
      containers:
        - env:
            - name: DB_CONNECTIONS
              value: "10"
            - name: DB_HOST
              value: 172.17.0.1
            - name: DB_NAME
              value: task
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_TIMEZONE
              value: Europe/London
            - name: DB_USERNAME
              value: postgres
            - name: SERVER_HOST
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "8080"
            - name: USE_ENVVAR
              value: "true"
          image: goserver
          name: go-server-stage
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
