version: "3.8"
services:
  server:
    build: .
    container_name: task-server
    environment:
      - USE_ENVVAR=true             
      - DB_HOST=task-db
      - DB_PORT=5432
      - DB_NAME=task
      - DB_TIMEZONE=Europe/London
      - DB_CONNECTIONS=10
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine3.19
    env_file: .env
    container_name: task-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=task

    volumes:
      - ./data/db:/var/lib/postgres/data
