apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: goserver-tcp
  name: goserver-tcp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: goserver
  type: LoadBalancer
